name: pg_fad
channels:
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.10.16
  - graphviz
  - pip:
      - accelerate==0.31.0
      - graphviz==0.20.3
      - datasets==2.20.0
      - evaluate==0.4.2
      - joblib==1.4.2
      - loralib==0.1.2
      - matplotlib==3.9.1
      - nltk==3.8.1
      - notebook==7.2.1
      - numpy==2.0.1
      - pandas==2.2.2
      - peft==0.12.0
      - requests==2.32.3
      - rouge-score==0.1.2
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - torch==2.4.0
      - torchvision==0.19.0
      - tqdm==4.66.5
      - transformers==4.44.0
